[package]
org = "samjs"
name = "scope"
version = "0.1.1"
authors = ["samjs"]
keywords = ["context", "request-scoped", "scope"]
repository = "https://github.com/sameerajayasoma/module-samjs-scope"
license = ["Apache-2.0"]
distribution = "2201.9.2"


[platform.java17]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.crates"
path = "../native/build/libs/scope-native-1.0.0-SNAPSHOT.jar"